### ISSUE TITLE
Ability to load PHP files instead of Pods templates

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods-frontier-auto-template#16]
Probably should only be set via filter not UI. Would need a filter for defining a location for these files. Would be cool if when loaded, magic tags could optionally be parsed. 

Would allow for an easy way to use the magic tag templateting system without using the Pods UI or to just have theme independent content parts.

**Comment by sc0ttkclark** [comment]
Closing, feel free to open this up on https://github.com/pods-framework/pods/issues now that Pods Frontier Auto Template is in Pods core.
