### ISSUE TITLE
Pods Frontier Auto Display Widget

### ISSUE THREAD

**Issue by lipaonline** [pods-framework/pods-frontier-auto-template#17]
Hello,
sometimes it will useful to put fields (all or part of) on widget.

You can add a option for "widget template"
add a widget, with no parameter, if we add it on sidebar, it will choose current pod, and display fields as we set on template.

**Comment by sc0ttkclark** [comment]
Closing, feel free to open this up on https://github.com/pods-framework/pods/issues now that Pods Frontier Auto Template is in Pods core.
