### ISSUE TITLE
Pods ACT + Pages Support

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods-frontier-auto-template#20]
Not sure if I really want to do this or not, but theoretically:

Would need to select Pods Page and Template in PFAT options and also would need to know url segments for Pod name and for slug. Output on pods_content filter, which means a method for setting which filter front() outputs on.

**Comment by sc0ttkclark** [comment]
Closing, feel free to open this up on https://github.com/pods-framework/pods/issues now that Pods Frontier Auto Template is in Pods core.
