### ISSUE TITLE
For extended post type Pods, base archive warning on post_type_supports()

### ISSUE THREAD

**Issue by Shelob9** [pods-framework/pods-frontier-auto-template#25]
Currently warning is thrown based on Pods Setting, but that doesn't apply to CPTs registered elsewhere. Check needs to differentiate based on extended post types vs Pods-registered post types, and if !=== registered by Pods , check using post_type_supports(). If that fails for extended post type, a more meaningful message is needed, probably using [add_post_type_support()](http://codex.wordpress.org/Function_Reference/add_post_type_support)

Related support thread:
http://wordpress.org/support/topic/connect-template-to-archive-with-extending-post-type?replies=1

**Comment by sc0ttkclark** [comment]
Closing, feel free to open this up on https://github.com/pods-framework/pods/issues now that Pods Frontier Auto Template is in Pods core.
