### ISSUE TITLE
Constant PODS_VERSION - assumed 'PODS_VERSION' Error when in debug

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-frontier-auto-template#30]
Reported in Pods main plugin by @chmchm https://github.com/pods-framework/pods/issues/3129

Got this error when I switched into debug after update to WP 4.3 Bille

Constant PODS_VERSION - assumed 'PODS_VERSION' in /blah/wp-content/plugins/pods-frontier-auto-template/pods-frontier-auto-template.php on line 47

**Comment by sc0ttkclark** [comment]
Solution should be that you load the plugin logic and the PODS_VERSION check once plugins_loaded hook runs. I'd suggest including another file with all of that only once plugins_loaded runs and the PODS_VERSION check passes.

**Comment by sc0ttkclark** [comment]
For reference, we think this issue happens when someone has Pods installed in a folder that is named in such a way that it loads after pods-frontier-auto-template. Such as when installing from GitHub, or having it named in alternative names (pods-master, etc).

**Comment by chmchm** [comment]
you mean in the plugins folder?
This is a screen shot of mine...



_______________________________________________________
Christina Morris
chmcreative.com | cmorris@me.com
214-458-6168  | 440-941-0555

**Comment by sc0ttkclark** [comment]
@chmchm try posting it directly to GitHub

**Comment by chmchm** [comment]
![screen shot 2015-09-09 at 2 47 57 pm](https://cloud.githubusercontent.com/assets/519471/9771565/08c8cb70-5705-11e5-8fce-6335cc150a03.png)

**Comment by chmchm** [comment]
![screen shot 2015-09-09 at 2 43 38 pm](https://cloud.githubusercontent.com/assets/519471/9771575/1c3f8748-5705-11e5-8433-cfb367e2191a.png)

**Comment by sc0ttkclark** [comment]
Looks like the normal pods folder name. Whatever the issue here, should be resolved with the plugins_loaded hook usageeg.

**Comment by sc0ttkclark** [comment]
Closing, feel free to open this up on https://github.com/pods-framework/pods/issues now that Pods Frontier Auto Template is in Pods core.
