### ISSUE TITLE
Taxonomy archive auto-template behaves incorrectly

### ISSUE THREAD

**Issue by clarinetlord** [pods-framework/pods-frontier-auto-template#31]
Steps to recreate:

1. Create custom taxonomy Pod, create post type Pod and assign taxonomy to post type
2. Create template to display fields for the post type Pod
3. Enable auto template on post type Pod and assign template to the "Archive view template"
4. Enable auto template on taxonomy Pod and assign the same template to the "Taxonomy template"

When viewing one of the taxonomy pages, the template does not assign `$this` to the Pods object for the post. The only workaround is to check for this and manually fetch the Pod using `get_the_ID()`. I'm guessing the current behavior is for a taxonomy archive template to assign `$this` to the Pods object for the taxonomy term. If that's the case, that makes no sense and is inconsistent with the rest of the loop functionality. An archive template for a post type should behave the same way whenever that post type is used in an archive loop a taxonomy loop or even a search loop.

**Comment by sc0ttkclark** [comment]
@jimtrue Needs moving to Pods repo or maybe this is already fixed in Pods core?

**Comment by sc0ttkclark** [comment]
Closing, feel free to open this up on https://github.com/pods-framework/pods/issues now that Pods Frontier Auto Template is in Pods core.
